<?php

return [
	'ROLE_TYPE_SUPER_ADMIN' => 1,
	'ROLE_TYPE_ADMIN' => 2,
	'ADMIN_ID_DEFAULT' => 1,
	'PRODUCT_IS_NEW' => 1,
	'PRODUCT_IS_OLD' => 0,
    'FRONTEND_LOGIN_TYPE_EMAIL' => 2,
    'USERS_STATUS_ACTIVE' => 1,
    'USERS_STATUS_BLOCK' => 2,
];
